[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/Fymyte/nvim-config.git"

[".config/qt5ct/colors/Catppuccin-Frappe.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/qt5ct/main/themes/Catppuccin-Frappe.conf"
  refreshPeriod = "168h"

[".config/polybar/catppuccin/colors/"]
  type = "archive"
  url = "https://codeload.github.com/catppuccin/polybar/zip/refs/heads/main"
  extract = true
  stripComponents = 2
  include = ["polybar-main/themes/**"]

[".cache/chezmoi/Colloid-theme"]
  type = "archive"
  url = "https://api.github.com/repos/vinceliuice/Colloid-icon-theme/tarball/main"
  refreshPeriod = "672h"
  extract = true
  stripComponents = 1

[".local/share/fonts/"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
  extract = true
