[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/Fymyte/nvim-config.git"

[".config/qt5ct/colors/Catppuccin-Frappe.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/qt5ct/main/Catppuccin-Frappe.conf"
  refreshPeriod = "168h"

[".config/polybar/catppuccin/colors/"]
  type = "archive"
  url = "https://codeload.github.com/catppuccin/polybar/zip/refs/heads/main"
  extract = true
  stripComponents = 2
  include = ["polybar-main/themes/**"]

[".local/share/icons/"]
  type = "archive"
  url = "https://raw.githubusercontent.com/catppuccin/cursors/main/cursors/Catppuccin-Frappe-Teal-Cursors.zip"
  extract = true

[".tmp/Colloid-theme"]
  type = "git-repo"
  url = "https://github.com/vinceliuice/Colloid-icon-theme"
  refreshPeriod = "168h"

[".local/share/fonts/"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
  extract = true
