[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/Fymyte/nvim-config.git"

[".cache/chezmoi/Colloid-theme"]
  type = "archive"
  url = "https://api.github.com/repos/vinceliuice/Colloid-icon-theme/tarball/main"
  refreshPeriod = "672h"
  extract = true
  stripComponents = 1
