keys:
  - users:
    - &fymyte age12qaxunhqmg8tcsyekeqaxqaf4c3aa0u5vk9fsccn04lvs34lrynqxlh03t
  - hosts:
    - &snorlax age17lyw7383njxcv2veeprxe47z9ketpjdsz3rw3vwkhedzz85tw3hq547wmv

creation_rules:
  - path_regex: secrets/[^/]+\.yaml
    key_groups:
      - age:
        - *fymyte
        - *snorlax
  - path_regex: secrets/fymyte/[^/]+\.(yaml|json)$
    key_groups:
      - age:
        - *fymyte
