keys:
  - users:
    - &sequans age1f62lase4vnjephq477jlp2wqwq82n2d9ygutsgjlq5mk5kszhelsfauylz 
    - &fymyte fill-me

creation_rules:
  - path_regex: secrets/sequans.ya?ml$
    key_groups:
      - age:
        - *sequans
  - path_regex: secrets/[^/]+\.(yaml|json)$
    key_groups:
      - age:
        - *fymyte
